---

- name: Create node
  bigip_node:
      server: "{{ inventory_hostname }}"
      user: "{{ bigip_username }}"
      password: "{{ bigip_password }}"
      state: present
      host: "9.9.9.9"
      name: "9.9.9.9"
      partition: "NETLAB"
  register: result

- name: Assert create node
  assert:
      that:
          - result|changed
